name: Publish To Github Packages
run-name: ${{ github.actor }} is publishing a new version of @aih-pkg/payload-ddb 🚀
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "pnpm"
          registry-url: 'https://npm.pkg.github.com'
          scope: '@aih-pkg'
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
